name: CI Scale Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scale-test:
    runs-on: ubuntu-latest
    steps:
      # Check out the repo for access
      - uses: actions/checkout@v2
      - name: Scale test
        env:
          SECRETS_JSON: ${{ secrets.SECRETS_JSON }}
        run: ./beeswarm.sh
