name: CI Scale Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scale-test:
    runs-on: ubuntu-latest
    steps:
      # Check out the repo for access
      - uses: actions/checkout@v2
      - name: Scale test
        env:
          GITHUB_PAT: ${{ secrets.GitHubPAT }}
          GDB_PASS: ${{ secrets.GDBPass }}
          CH_IMAGE_USER: ${{ secrets.ChImageUser }}
          CH_IMAGE_PASSWORD: ${{ secrets.ChImagePassword }}
        run: ./ci-scale-test.sh
